[project]
name = "accuknox-sq-sast"
version = "0.1.1"
description = "AccuKnox ASPM Scanner"
authors = [{ name = "AccuKnox", email = "accuknox@accuknox.com" }]

dependencies = [
    "aiohttp>=3.9,<4",
    "tqdm==4.67.1",
    "colorama==0.4.6"
]

[project.scripts]
accuknox-sq-sast = "accuknox_sq_sast.cli:main"
