name: Publish Docker image on tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  tag-validate:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: rubenesp87/semver-validation-action@0.1.0
      with:
        version: ${{ github.ref_name }}

  pip-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tool
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@39ba0b9d81217c984acfad95ddcc7db226387497
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          generate_release_notes: true
          files: dist/*

  push_to_ecr:
    needs: tag-validate
    name: Push Docker image to ECR Public
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to AWS ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws/k9v9d5v2

      - name: Extract Tag Name
        id: extract_tag
        run: echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build & Push Docker Image to ECR Public
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag public.ecr.aws/k9v9d5v2/aspm-sastjob:${{ env.RELEASE_TAG }} \
            --push \
            .
