name: Publish Docker image on tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"  
      - "[0-9]+.[0-9]+.[0-9]+-*" 
      
jobs:
  tag-validate:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: rubenesp87/semver-validation-action@0.1.0
      with:
       version: ${{ github.ref_name }}

  pip-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tool
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@39ba0b9d81217c984acfad95ddcc7db226387497
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          generate_release_notes: true
          files: dist/*

  push_to_registry:
    needs: tag-validate
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract Tag Name
        id: extract_tag
        run: echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build & Push image to Docker Hub
        run: make docker-buildx IMGTAG=${{ env.RELEASE_TAG }}
